### ISSUE TITLE
Services file's missing

### ISSUE THREAD

**Issue by Arnaud-D** [driftyco/ionic-starter-io#1]
Hey everyone!

Just to let you know that when you run the fresh application without editing a thing, an error is shown. The starter.services module cannot be loaded because there is no such file in /js directory.

Edit: I've seen you removed the file recently, and you forgot to edit the app.js file as well.

Hope it helps.

**Comment by Fuiste** [comment]
Whoops, forgot to remove that from one of the starter templates.  Good Catch!

It should work now.
